# Generated by Django 6.0.7 on 2026-09-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_edited', models.DateTimeField(auto_created=True)),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Porducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_edited', models.DateTimeField(auto_created=True)),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField()),
                ('product_price_new', models.FloatField(default=0)),
                ('product_price_old', models.FloatField(default=0)),
                ('base_price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='product_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
        ),
    ]
