# Generated by Django 6.0.7 on 2026-09-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porducts',
            new_name='Products',
        ),
    ]
